# pairing.jl
#
# Validates the purely combinatorial `double_leaves` construction against
# Hecke-algebra ground truth: the Bott–Samelson Soergel-pairing table
# (data/pairing/a3-bs-pairing.txt, generated by
# an independent Oscar computation and read via
# `bs_pairing`/`expected_count`, src/algebra/Pairing.jl).
#
# For every pair of A3 words with length(x) <= 3 and length(y) <= 3 present in
# the table:
#     expected_count(x, y) == length(double_leaves(x, y))
# and per degree d present in the table entry:
#     expected_count(x, y; degree = d) == length(double_leaves(x, y; degree = d))
#
# A mismatch here is a REAL finding (either in double_leaves or in the ground
# truth) — do not adjust this test to make it pass.

@testset "Bott-Samelson pairing vs Hecke-algebra ground truth" begin
    table = pairing_table()
    small_keys = [(x, y) for (x, y) in keys(table) if length(x) <= 3 && length(y) <= 3]
    @test length(small_keys) > 0

    for (x, y) in small_keys
        expected_total = expected_count(x, y)
        actual_total = length(double_leaves(x, y))
        @test actual_total == expected_total

        for d in keys(table[(x, y)])
            expected_d = expected_count(x, y; degree = d)
            actual_d = length(double_leaves(x, y; degree = d))
            @test actual_d == expected_d
        end
    end
end

# The degree invariant of the circular-leaf reduction + test 1 PER DEGREE
# (src/circular/rules/CircularLeafDegree.jl). A pair on which the ungraded test 1 passes — then
# EVERY degree must agree too.
@testset "circular-leaf degree invariant + test1_graded on (121, 121)" begin
    x = [1, 2, 1]
    dls = double_leaves(x, x)
    leaf_degrees = Int[]
    seen = Set{Any}()
    for d in dls
        fm = circular_morphism(d.morphism)
        fdm = CircularDecoratedMorphism(fm, fill(one(SoergelPoly), region_count(fm.graph)))
        combo = reduce_to_circular_leave(fdm)
        # the invariant: degree(DL) == degree(p) + circular_degree(FL) on EVERY term
        @test isempty(circular_degree_violations(d.degree, combo))
        for (fd, _) in pairs_of(combo)
            k = circular_canonical_key(fd)
            k in seen && continue
            push!(seen, k)
            push!(leaf_degrees, circular_degree(fd))
        end
    end
    @test length(leaf_degrees) == length(dls)          # the ungraded test1 count

    r = test1_graded(x, x, [d.degree for d in dls], leaf_degrees)
    @test r.consistent
    # the table knows (121,121): 0:2 2:5 4:4 6:1 — every row must match
    @test [(row.degree, row.n_dl, row.pairing) for row in r.rows] ==
          [(0, 2, 2), (2, 5, 5), (4, 4, 4), (6, 1, 1)]
    @test all(row.excess == 0 for row in r.rows)
end

# COUNTING RULE: a leaf occurring ONLY with a polynomial coefficient does not
# count as a circular leaf of its own. `circular_leaf_degrees` (src/circular/rules/CircularLeafDegree.jl)
# implements that.
@testset "circular_leaf_degrees — only leaves with a scalar coefficient" begin
    x = [1, 2, 1]
    dls = double_leaves(x, x)
    combos = [begin
                  fm  = circular_morphism(d.morphism)
                  fdm = CircularDecoratedMorphism(fm, fill(one(SoergelPoly),
                                                     region_count(fm.graph)))
                  reduce_to_circular_leave(fdm)
              end for d in dls]

    alle = circular_leaf_degrees(combos; scalar_only = false)
    rein = circular_leaf_degrees(combos)

    @test alle.dropped == 0
    @test length(alle.degrees) == length(dls)              # the ungraded test1 count
    # The filtered list is a SUBlist of the unfiltered one.
    @test length(rein.degrees) + rein.dropped == length(alle.degrees)
    @test issubset(keys(rein.index), keys(alle.index))
    # `index` numbers 1..n without gaps, matching `degrees`.
    @test sort(collect(values(rein.index))) == collect(1:length(rein.degrees))

    # On (121,121) test 1 passes exactly — no leaf drops out here, and the
    # the graded table stays consistent.
    @test rein.dropped == 0
    @test test1_graded(x, x, [d.degree for d in dls], rein.degrees).consistent
end

